### ISSUE TITLE
Is it a necessity that training the data before predict circRNA-RBP pairs ?

### ISSUE THREAD

**Issue by gnilihzeux** [houzl3416/iCircRBP-DHN#2]
Dear author,
  As the title says, could this program use like a wrapped software, which only needs the input & output.

  Secondly, whether should I training the clip-seq data  for a new RBP which is not in your dataset ?

  Thank you.

**Comment by houzl3416** [comment]
About your question, now we have not provided a wrapped software.But I think you can solve your problem in this way below:
We have provided&nbsp;linRNA2Vec_model&nbsp;and clip-seq in our github. You can change the input-model and input-dataset(your own data is also allowed but you need attend your data format) in&nbsp;iCircRBP-DHN.py
Then you can get a h5 model ,you can use this model in&nbsp;iCircRBP-Predict.py&nbsp;.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "houzl3416/iCircRBP-DHN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 上午10:14
收件人:&nbsp;"houzl3416/iCircRBP-DHN"<iCircRBP-DHN@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[houzl3416/iCircRBP-DHN] Is it a necessity that training the data before predict circRNA-RBP pairs ? (#2)





 
Dear author,
 As the title says, could this program use like a wrapped software, which only needs the input &amp; output.
 
Secondly, whether should I training the clip-seq data  for a new RBP which is not in your dataset ?
 
Thank you.

**Comment by gnilihzeux** [comment]
Thanks for your reply. I'll try it.
