### ISSUE TITLE
Other ways to share "linRNA2Vec/linRNA2Vec.txt"?

### ISSUE THREAD

**Issue by isPrettyBoy** [houzl3416/iCircRBP-DHN#3]
Hi there,

In the last month, I tried to clone this repo 8 times a day. But always got the following error due to the git LFS limitation of your account. Can you please share the **linRNA2Vec/linRNA2Vec.txt** file over Google Drive, Dropbox or Baidu Pan with us?

Thanks!

```bash
remote: Enumerating objects: 753, done.
remote: Counting objects: 100% (753/753), done.
remote: Compressing objects: 100% (609/609), done.
remote: Total 753 (delta 112), reused 748 (delta 112), pack-reused 0
Receiving objects: 100% (753/753), 161.91 MiB | 13.98 MiB/s, done.
Resolving deltas: 100% (112/112), done.
Checking out files: 100% (590/590), done.
Downloading linRNA2Vec/linRNA2Vec.txt (96 MB)
Error downloading object: linRNA2Vec/linRNA2Vec.txt (898ef52): Smudge error: Error downloading linRNA2Vec/linRNA2Vec.txt (898ef521c51f2fc1885d00485ac7ecbe8ffef2aa069b113e3cef0eff8c51aad5): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by Rebecca3150** [comment]
Me, too. I have been waiting for a month, but I still can't download it. So I hope you can provide another link for downloading.

**Comment by houzl3416** [comment]
Because the file is too large, the file was not uploaded completely before, I will upload it to github within a few hours, I'm very sorry

**Comment by isPrettyBoy** [comment]
@houzl3416 Many thanks! My two cents, GitHub only limits the size of each single file ([as per the doc: 100MB](https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota)) but not the total size of the repo, you may use the `split` command to split the large file into small pieces.

**Comment by houzl3416** [comment]
> @houzl3416 Many thanks! My two cents, GitHub only limits the size of each single file ([as per the doc: 100MB](https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota)) but not the total size of the repo, you may use the `split` command to split the large file into small pieces.

I uploaded it to Google Drive, welcome to download.

**Comment by houzl3416** [comment]
> Me, too. I have been waiting for a month, but I still can't download it. So I hope you can provide another link for downloading.

I uploaded it to Google Drive, welcome to download.
